{ config, lib, pkgs, ... }:

let
  # Host-local variables (keep secrets out of git)
  vars = import ../../vars/local.nix;
in
{
  imports = [
    ./hardware-configuration.nix        # Hardware-specific settings generated by NixOS
    ../../profiles/server.nix           # Server baseline (includes users via modules/users.nix)
    ../../modules/remote-unlock.nix     # Optional: initrd SSH for remote LUKS unlock
  ];

  # Pass vars to modules that accept `vars` as an argument
  _module.args = { inherit vars; };

  # ---------------------------------------------------------------------------
  # Hardening overrides (server profile enables hardening; host can override details)
  # ---------------------------------------------------------------------------

  # Keep logs across reboots (recommended for servers)
  flowback.hardening.journaldVolatile = false;

  # Rootless containers need this; keep it true
  flowback.hardening.allowUserNamespaces = true;

  # ---------------------------------------------------------------------------
  # Sudo policy
  # NOTE: If wheelNeedsPassword=true, make sure your main user has a password
  # (via hashedPasswordFile in vars + /etc/secrets, or set wheelNeedsPassword=false).
  # ---------------------------------------------------------------------------
  security.sudo.wheelNeedsPassword = true;

  # ---------------------------------------------------------------------------
  # Networking (host-specific)
  # ---------------------------------------------------------------------------
  networking.hostName = vars.hostName;
  networking.useDHCP = false;

  networking.interfaces.${vars.iface} = {
    useDHCP = false;
    ipv4.addresses = [{
      address = vars.ip;
      prefixLength = vars.prefixLength;
    }];
  };

  networking.defaultGateway = vars.gateway;
  networking.nameservers = vars.nameservers;

  # Local host overrides (affects THIS host only; clients still need DNS/hosts)
  networking.extraHosts = ''
    127.0.0.1 ${vars.forgejoHost}
    ${vars.forgejoIp} ${vars.forgejoHost}
  '';

  networking.firewall = {
    enable = true;
    allowedTCPPorts = vars.allowedTCPPorts;  # Open only the ports you explicitly allow
  };
}

