{ config, lib, pkgs, ... }:

let
  # Host-local variables (keep secrets out of git)
  vars = import ../../vars/local.nix;
in
{
  imports = [
    ./hardware-configuration.nix        # Hardware-specific settings generated by NixOS
    ../../modules/base.nix              # Base OS + security defaults + core packages
    ../../modules/aliases.nix           # Shell aliases (fb-up, fb-logs, nix-switch, etc.)
    ../../modules/remote-unlock.nix     # Optional: initrd SSH for remote LUKS unlock
    ../../modules/hardening.nix         # Extra security
    ../../modules/prompt-timestamp.nix  # Time stamp for user shellpromt
  ];

  # Pass vars to modules that accept `vars` as an argument
  _module.args = { inherit vars; };
  
  # Enable Hardening
  flowback.hardening.enable = true;
  
  # Keep logs across reboots (recommended for servers)
  flowback.hardening.journaldVolatile = false;
  
  # Rootless Docker needs this; keep it true
  flowback.hardening.allowUserNamespaces = true;
  
  # Enable timestamp
  flowback.promptTimestamp.enable = true;
  
   users.users.ayuub = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "docker" ];   # sudo + networking + docker group
    openssh.authorizedKeys.keys = vars.authorizedKeys;     # SSH keys for user login
  };

  security.sudo.wheelNeedsPassword = true;                 # sudo requires password for wheel users

  networking.hostName = vars.hostName;                     # Hostname used by system + mDNS (if enabled)

  networking.useDHCP = false;                              # Static networking (no DHCP)

  # Static IPv4 config for the primary interface
  networking.interfaces.${vars.iface} = {
    useDHCP = false;
    ipv4.addresses = [{
      address = vars.ip;
      prefixLength = vars.prefixLength;
    }];
  };

  networking.defaultGateway = vars.gateway;                # Default route
  networking.nameservers = vars.nameservers;               # DNS servers

  # Local host overrides (useful for internal services)
  networking.extraHosts = ''
    127.0.0.1 ${vars.forgejoHost}
    ${vars.forgejoIp} ${vars.forgejoHost}
  '';

  networking.firewall = {
    enable = true;                                         # Firewall on by default
    allowedTCPPorts = vars.allowedTCPPorts;                # Open only the ports you explicitly allow
  };
}

